# Site settings
title: Data Droid Blog
description: 데이터 엔지니어가 다루는 기술 블로그
author: Data Droid
email: blue44rain@gmail.com
url: "https://data-droid.github.io"
baseurl: ""

# Language settings
languages: ["ko", "en"]
default_lang: "ko"
exclude_from_localization: ["assets", "images", "js", "css"]

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /:collection/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Data Droid"
      comments: false
      share: true

# Plugins (commented out for GitHub Pages compatibility)
# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag
#   - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Pagination (commented out for GitHub Pages compatibility)
# paginate: 5
# paginate_path: "/page/:num/"

# Social media
twitter_username: your-twitter-username
github_username: data-droid
linkedin_username: your-linkedin-username

# Analytics
google_analytics: G-GP9LT745PP  # 여기에 실제 GA4 측정 ID를 입력하세요

# Comments
disqus_shortname: your-disqus-shortname

# Theme (using custom layout)
# theme: jekyll-theme-minimal

# Navigation
navigation:
  - title: 홈
    url: /
  - title: 데이터 엔지니어링
    url: /categories/data-engineering/
  - title: BI 엔지니어링
    url: /categories/bi-engineering/
  - title: 시스템 아키텍처
    url: /categories/system-architecture/
  - title: 데이터 품질
    url: /categories/data-quality/
  - title: 개발 도구
    url: /categories/dev-tools/
  - title: 블로그
    url: /blog/
  - title: 소개
    url: /about/